export const language = {
    eng: {
        play: "Play",
        back: "Back",
        flips_text: "Number of flips",
        score: "Best score",
        solve: "Solve",
        randomize: "Randomize",
        restart: "Restart",
        add: "Add",
        remove: "Remove",
        lang: "FR",
        winMessage: 'Congratulations. The crepes are sorted',
        how_to_play_title: `How to play:`,
        how_to_play_description: `You can flip stacks of pancakes: by double-clicking on a pancake,the stack of pancakes above it flips and is upside down.You can zoom in/out and flip the stack back and forth. By pressing Shift and the left mouse button, it is possible to move the stack of pancakes.`,
        game_rule_title: `Game rule:`,
        game_rule_description: `You must sort the pancakes from smallest on top to largest on bottom.`,
        link_text: "more info",
        timer: "Timer"
    },
    fr: {
        play: "Jouer",
        back: "Retour",
        flips_text: "Nombre de retournements",
        score: "Meilleur score",
        solve: "Résoudre",
        randomize: "Mélanger",
        restart: "Recommencer",
        add: "Ajouter",
        remove: "Supprimer",
        lang: "EN",
        winMessage: "Félicitations. Les crêpes sont triées",
        how_to_play_title: `Comment jouer:`,
        how_to_play_description: `Vous pouvez retourner des piles de crêpes : en double-cliquant sur une crêpe, la pile de crêpes au-dessus d'elle se retourne et se retrouve à l'envers.Vous pouvez effectuer un zoom avant/arrière et retourner la pile d'avant en arrière. En appuyant sur Maj et le bouton gauche de la souris, il est possible de déplacer la pile de crêpes.`,
        game_rule_title: `Régles de jeu:`,
        game_rule_description: `Vous devez trier les crêpes de la plus petite en haut à la plus grande en bas.`,
        link_text: "plus d'info",
        timer: "Chronomètre"
    }
}